spring:
  datasource:
    druid:
      url: jdbc:mysql://144.34.204.209:3306/mmall?useUnicode=true&characterEncoding=utf8&autoReconnect=true&useSSL=false&serverTimezone=UTC
      username: root
      password: guoyou
      driverClassName: com.mysql.cj.jdbc.Driver
      # 连接池配置 初始化大小、最小、最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      #配置获取连接等待超时的时间
      max-wait: 60000
      #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 20000
      #配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 from dual
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
  #mybitis
mybatis:
  mapper-locations: classpath:/mappers/**.xml
  type-aliases-package: com.example.mmallshopping.pojo
  #sql日志打印
  check-config-location: true
mybatis-plus:
  configuration.log-impl: org.apache.ibatis.logging.stdout.StdOutImpl